# Generated by Django 2.2.3 on 2019-07-16 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('b_day', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('skype', models.CharField(blank=True, max_length=250, verbose_name='Skype')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('about', models.TextField(blank=True, verbose_name='message')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
