# Generated by Django 2.2.3 on 2019-08-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
