# Generated by Django 2.2.3 on 2019-08-04 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='message')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('read', models.BooleanField(verbose_name='Прочитано')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_r', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_s', to=settings.AUTH_USER_MODEL, verbose_name='Отправыитель')),
            ],
        ),
        migrations.RenameField('Post', 'post', 'text'),
        migrations.RenameField('Comment', 'comment', 'text'),
    ]
